function powsys = admittance_matrix(powsys)
% --------------------- Unified branch model -------------------------------
powsys.ybus.admittance = 1 ./ (powsys.branch.resistance + 1i .* ...
                           powsys.branch.reactance);
isLine = ~powsys.branch.transturns;
powsys.ybus.transformerRatio(isLine) = exp(1i .* powsys.branch.transphase(isLine));
powsys.ybus.transformerRatio(~isLine) = powsys.branch.transturns(~isLine)...
                              .* exp(1i * powsys.branch.transphase(~isLine));
transformerRatioConj = conj(powsys.ybus.transformerRatio);
powsys.ybus.nodalToTo =  powsys.ybus.admittance + 1i / 2 .* powsys.branch.charging;
powsys.ybus.nodalFromFrom =  powsys.ybus.nodalToTo ./ ...
            (transformerRatioConj .* powsys.ybus.transformerRatio).';
powsys.ybus.nodalFromTo = -powsys.ybus.admittance ./ transformerRatioConj.';
powsys.ybus.nodalToFrom = -powsys.ybus.admittance ./ ...
                                   powsys.ybus.transformerRatio.';
% -------------------------------------------------------------------------

% ---------------------------- Diagonal elements in Y ---------------------
powsys.ybus.ydiag = accumarray([powsys.branch.i; powsys.branch.j ],...
    [powsys.ybus.nodalFromFrom; powsys.ybus.nodalToTo ], [powsys.num.bus, 1] ) ...
    + powsys.bus.Gshunt + 1i .* powsys.bus.Bshunt;
% -------------------------------------------------------------------------

% -------------------- Compose sparse matrices ----------------------------
powsys.ybus.y = sparse([ powsys.bus.busnew; powsys.branch.i;...
                                    powsys.branch.j ], [powsys.bus.busnew; ...
                                   powsys.branch.j; powsys.branch.i], ...
                            [ powsys.ybus.ydiag; powsys.ybus.nodalFromTo; powsys.ybus.nodalToFrom], ...
                             powsys.num.bus, powsys.num.bus);
powsys.ybus.yij = sparse([ powsys.branch.i; powsys.branch.j ], ...
        [ powsys.branch.j, powsys.branch.i], [ powsys.ybus.nodalFromTo; ...
         powsys.ybus.nodalToFrom], powsys.num.bus, powsys.num.bus);                       
powsys.ybus.yT = transpose(powsys.ybus.y);  
% -------------------------------------------------------------------------
end



